### PR TITLE
Use FingerprintManager instead of FingerprintManagerCompat (Fix #300)

### LINKED ISSUE #300: Fingerprint Sensor not recognized (no fingerprint option)
i just moved my primary phone from LG G5 to Nubia Z17mini

while both phones have fingerprint sensor. i failed to see the option on the Nubia. (no problem with the LG G5, option is available..)

the fingerprint sensor on the Nubia is 100% working as recognized in other apps, as well for unlocking the phone.

PS: the nubia still in Marshmallow, while the LG is Nougat, if it matter.

### PR DESCRIPTION
**Pull request by 0140454**

### CODE REVIEW

File: app/src/main/java/com/m2049r/xmrwallet/util/FingerprintHelper.java [hunk 1]
```diff
@@ -2,18 +2,21 @@
...
-        KeyguardManager keyguardManager = (KeyguardManager) context.getSystemService(Context.KEYGUARD_SERVICE);
+        if (Build.VERSION.SDK_INT < Build.VERSION_CODES.M) {
+            return false;
+        }
+
+        FingerprintManager fingerprintManager = context.getSystemService(FingerprintManager.class);
+        KeyguardManager keyguardManager = context.getSystemService(KeyguardManager.class);
 
-        return keyguardManager != null &&
+        return keyguardManager != null && fingerprintManager != null &&
```
Comment (m2049r) [inline app/src/main/java/com/m2049r/xmrwallet/util/FingerprintHelper.java]: @0140454 please use brackets around subexpressions: ```return (keyguardManager != null) && (fingerprintManager != null) && ...``` for legibility

**Comment by m2049r** [comment]
If I merge #297 into master, could you rebase this off that - I am having a hard time figuring out what's right!

**Comment by 0140454** [comment]
@m2049r 
Sure, I will rebase branch after you merge the PR.

**Review by m2049r — APPROVED** [review]
